// src/react/react-frontend/src/components/TrainerPokemon.js
import React, { useState, useEffect } from 'react';
import { trainerPokemonAPI, pokemonAPI } from '../services/api';
import './TrainerPokemon.css';

function TrainerPokemon({ trainer, onBack }) {
  const [pokemon, setPokemon] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  // State for add Pokemon form
  const [showAddForm, setShowAddForm] = useState(false);
  const [availablePokemon, setAvailablePokemon] = useState([]);
  const [newPokemon, setNewPokemon] = useState({
    pokemon_id: '',
    nickname: '',
    level: 5
  });
  const [submitting, setSubmitting] = useState(false);
  // State for editing Pokemon
  const [editingPokemon, setEditingPokemon] = useState(null);
  const [editPokemonData, setEditPokemonData] = useState({
    nickname: '',
    level: 5
  });

  useEffect(() => {
    fetchTrainerPokemon();
    fetchAvailablePokemon();
  }, [trainer.id]);

  const fetchTrainerPokemon = async () => {
    try {
      setLoading(true);
      setError(null);
      
      const data = await trainerPokemonAPI.getTrainerPokemon(trainer.id);
      console.log('Fetched trainer Pokemon:', data);
      
      setPokemon(data);
    } catch (err) {
      console.error('Error fetching trainer Pokemon:', err);
      setError('Failed to load Pokemon for this trainer.');
    } finally {
      setLoading(false);
    }
  };

  const fetchAvailablePokemon = async () => {
    try {
      const data = await pokemonAPI.getAllPokemon();
      console.log('Fetched available Pokemon:', data);
      setAvailablePokemon(data);
    } catch (err) {
      console.error('Error fetching available Pokemon:', err);
    }
  };

  // Handle form input changes for new Pokemon
  const handleAddPokemonInputChange = (e) => {
    const { name, value } = e.target;
    setNewPokemon(prev => ({
      ...prev,
      [name]: value
    }));
  };

  // Handle form input changes for editing Pokemon
  const handleEditPokemonInputChange = (e) => {
    const { name, value } = e.target;
    setEditPokemonData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  // Handle adding Pokemon to trainer
  const handleAddPokemon = async (e) => {
    e.preventDefault();
    
    if (!newPokemon.pokemon_id) {
      alert('Please select a Pokemon!');
      return;
    }

    if (newPokemon.level < 1 || newPokemon.level > 100) {
      alert('Level must be between 1 and 100!');
      return;
    }

    try {
      setSubmitting(true);
      
      // Prepare data for API
      const pokemonData = {
        pokemon_id: parseInt(newPokemon.pokemon_id),
        nickname: newPokemon.nickname.trim() || null,
        level: parseInt(newPokemon.level)
      };

      // Call API to add Pokemon to trainer
      const addedPokemon = await trainerPokemonAPI.addPokemonToTrainer(trainer.id, pokemonData);
      console.log('Added Pokemon to trainer:', addedPokemon);

      // Reset form
      setNewPokemon({
        pokemon_id: '',
        nickname: '',
        level: 5
      });
      setShowAddForm(false);

      // Refresh the Pokemon list
      await fetchTrainerPokemon();

    } catch (err) {
      console.error('Error adding Pokemon to trainer:', err);
      alert('Failed to add Pokemon. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  // Start editing a Pokemon
  const startEditingPokemon = (pokemonItem) => {
    setEditingPokemon(pokemonItem.id);
    setEditPokemonData({
      nickname: pokemonItem.nickname || '',
      level: pokemonItem.level
    });
    setShowAddForm(false); // Close add form if open
  };

  // Cancel editing Pokemon
  const cancelEditingPokemon = () => {
    setEditingPokemon(null);
    setEditPokemonData({
      nickname: '',
      level: 5
    });
  };

  // Handle edit Pokemon form submission
  const handleEditPokemon = async (e) => {
    e.preventDefault();
    
    if (editPokemonData.level < 1 || editPokemonData.level > 100) {
      alert('Level must be between 1 and 100!');
      return;
    }

    try {
      setSubmitting(true);
      
      // Prepare data for API
      const pokemonData = {
        nickname: editPokemonData.nickname.trim() || null,
        level: parseInt(editPokemonData.level)
      };

      // Call API to update Pokemon
      const updatedPokemon = await trainerPokemonAPI.updateTrainerPokemon(trainer.id, editingPokemon, pokemonData);
      console.log('Updated Pokemon:', updatedPokemon);

      // Cancel editing
      cancelEditingPokemon();

      // Refresh the Pokemon list
      await fetchTrainerPokemon();

    } catch (err) {
      console.error('Error updating Pokemon:', err);
      alert('Failed to update Pokemon. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  // Handle Pokemon deletion
  const handleDeletePokemon = async (pokemonId, pokemonName) => {
    const confirmDelete = window.confirm(
      `Are you sure you want to remove ${pokemonName} from ${trainer.name}'s team? This action cannot be undone.`
    );

    if (!confirmDelete) {
      return;
    }

    try {
      await trainerPokemonAPI.deleteTrainerPokemon(trainer.id, pokemonId);
      console.log('Deleted Pokemon:', pokemonId);
      
      // Refresh the Pokemon list
      await fetchTrainerPokemon();
      
      // Cancel editing if we were editing this Pokemon
      if (editingPokemon === pokemonId) {
        cancelEditingPokemon();
      }

    } catch (err) {
      console.error('Error deleting Pokemon:', err);
      alert('Failed to remove Pokemon. Please try again.');
    }
  };

  // Get selected Pokemon details for display
  const getSelectedPokemonInfo = () => {
    if (!newPokemon.pokemon_id) return null;
    return availablePokemon.find(p => p.id === parseInt(newPokemon.pokemon_id));
  };

  if (loading) {
    return (
      <div className="trainer-pokemon-container">
        <div className="trainer-pokemon-header">
          <button onClick={onBack} className="back-button">← Back to Trainers</button>
          <h2>Loading {trainer.name}'s Pokemon...</h2>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="trainer-pokemon-container">
        <div className="trainer-pokemon-header">
          <button onClick={onBack} className="back-button">← Back to Trainers</button>
          <h2>{trainer.name}'s Pokemon Team</h2>
        </div>
        <div className="error-message">{error}</div>
        <button onClick={fetchTrainerPokemon} className="retry-button">
          Retry
        </button>
      </div>
    );
  }

  const selectedPokemonInfo = getSelectedPokemonInfo();

  return (
    <div className="trainer-pokemon-container">
      <div className="trainer-pokemon-header">
        <button onClick={onBack} className="back-button">← Back to Trainers</button>
        <div className="trainer-info">
          <h2>{trainer.name}'s Pokemon Team</h2>
          <p className="pokemon-count">{pokemon.length} Pokemon</p>
        </div>
        <button 
          onClick={() => {
            setShowAddForm(!showAddForm);
            if (editingPokemon) cancelEditingPokemon(); // Cancel editing if adding new Pokemon
          }} 
          className="add-pokemon-button"
        >
          {showAddForm ? 'Cancel' : 'Add Pokemon'}
        </button>
      </div>

      {/* Add Pokemon Form */}
      {showAddForm && !editingPokemon && (
        <div className="add-pokemon-form">
          <h3>Add Pokemon to {trainer.name}'s Team</h3>
          <form onSubmit={handleAddPokemon}>
            <div className="form-group">
              <label htmlFor="pokemon_id">Select Pokemon (required):</label>
              <select
                id="pokemon_id"
                name="pokemon_id"
                value={newPokemon.pokemon_id}
                onChange={handleAddPokemonInputChange}
                required
              >
                <option value="">Choose a Pokemon...</option>
                {availablePokemon.map((p) => (
                  <option key={p.id} value={p.id}>
                    #{p.id.toString().padStart(3, '0')} - {p.name} ({p.type1}{p.type2 ? ` / ${p.type2}` : ''})
                  </option>
                ))}
              </select>
            </div>

            {selectedPokemonInfo && (
              <div className="selected-pokemon-preview">
                <h4>Selected: {selectedPokemonInfo.name}</h4>
                <p><strong>Type:</strong> {selectedPokemonInfo.type1}{selectedPokemonInfo.type2 ? ` / ${selectedPokemonInfo.type2}` : ''}</p>
                <p><strong>Base Stats:</strong> HP: {selectedPokemonInfo.hp}, ATK: {selectedPokemonInfo.attack}, DEF: {selectedPokemonInfo.defense}, SPD: {selectedPokemonInfo.speed}, SPC: {selectedPokemonInfo.special}</p>
              </div>
            )}

            <div className="form-group">
              <label htmlFor="nickname">Nickname (optional):</label>
              <input
                type="text"
                id="nickname"
                name="nickname"
                value={newPokemon.nickname}
                onChange={handleAddPokemonInputChange}
                placeholder="Leave blank to use Pokemon name"
                maxLength="20"
              />
            </div>

            <div className="form-group">
              <label htmlFor="level">Level (1-100):</label>
              <input
                type="number"
                id="level"
                name="level"
                value={newPokemon.level}
                onChange={handleAddPokemonInputChange}
                min="1"
                max="100"
                required
              />
            </div>

            <div className="form-buttons">
              <button 
                type="submit" 
                disabled={submitting}
                className="submit-button"
              >
                {submitting ? 'Adding Pokemon...' : 'Add Pokemon'}
              </button>
              <button 
                type="button" 
                onClick={() => setShowAddForm(false)}
                className="cancel-button"
              >
                Cancel
              </button>
            </div>
          </form>
          <p className="form-note">
            <strong>Note:</strong> IVs (Individual Values) will be randomly generated for this Pokemon.
          </p>
        </div>
      )}

      {pokemon.length === 0 ? (
        <div className="no-pokemon">
          <p>This trainer doesn't have any Pokemon yet.</p>
          <p>Click "Add Pokemon" to get started!</p>
        </div>
      ) : (
        <div className="pokemon-grid">
          {pokemon.map((p) => (
            <div key={p.id} className="pokemon-card">
              {editingPokemon === p.id ? (
                // Edit form for Pokemon
                <div className="edit-pokemon-form">
                  <h3>Edit {p.nickname || p.pokemon_name}</h3>
                  <form onSubmit={handleEditPokemon}>
                    <div className="form-group">
                      <label htmlFor={`edit-nickname-${p.id}`}>Nickname (optional):</label>
                      <input
                        type="text"
                        id={`edit-nickname-${p.id}`}
                        name="nickname"
                        value={editPokemonData.nickname}
                        onChange={handleEditPokemonInputChange}
                        placeholder="Leave blank to use Pokemon name"
                        maxLength="20"
                      />
                    </div>

                    <div className="form-group">
                      <label htmlFor={`edit-level-${p.id}`}>Level (1-100):</label>
                      <input
                        type="number"
                        id={`edit-level-${p.id}`}
                        name="level"
                        value={editPokemonData.level}
                        onChange={handleEditPokemonInputChange}
                        min="1"
                        max="100"
                        required
                      />
                    </div>

                    <div className="form-buttons">
                      <button 
                        type="submit" 
                        disabled={submitting}
                        className="submit-button"
                      >
                        {submitting ? 'Updating...' : 'Update Pokemon'}
                      </button>
                      <button 
                        type="button" 
                        onClick={cancelEditingPokemon}
                        className="cancel-button"
                      >
                        Cancel
                      </button>
                    </div>
                  </form>
                  <p className="form-note">
                    <strong>Note:</strong> Changing the level will recalculate stats but keep the same IVs.
                  </p>
                </div>
              ) : (
                // Display Pokemon info
                <>
                  <div className="pokemon-header">
                    <h3>{p.nickname || p.pokemon_name}</h3>
                    {p.nickname && <p className="pokemon-species">({p.pokemon_name})</p>}
                  </div>
                  
                  <div className="pokemon-info">
                    <p><strong>Level:</strong> {p.level}</p>
                    <p><strong>Type:</strong> {p.type1}{p.type2 ? ` / ${p.type2}` : ''}</p>
                  </div>

                  <div className="pokemon-stats">
                    <h4>Stats</h4>
                    <div className="stats-grid">
                      <div className="stat">
                        <span className="stat-name">HP</span>
                        <span className="stat-value">{p.calculated_hp}</span>
                      </div>
                      <div className="stat">
                        <span className="stat-name">Attack</span>
                        <span className="stat-value">{p.calculated_attack}</span>
                      </div>
                      <div className="stat">
                        <span className="stat-name">Defense</span>
                        <span className="stat-value">{p.calculated_defense}</span>
                      </div>
                      <div className="stat">
                        <span className="stat-name">Speed</span>
                        <span className="stat-value">{p.calculated_speed}</span>
                      </div>
                      <div className="stat">
                        <span className="stat-name">Special</span>
                        <span className="stat-value">{p.calculated_special}</span>
                      </div>
                    </div>
                  </div>

                  <div className="pokemon-ivs">
                    <h4>IVs (Individual Values)</h4>
                    <div className="ivs-grid">
                      <span>ATK: {p.iv_attack}</span>
                      <span>DEF: {p.iv_defense}</span>
                      <span>SPD: {p.iv_speed}</span>
                      <span>SPC: {p.iv_special}</span>
                    </div>
                  </div>

                  <div className="pokemon-actions">
                    <button 
                      onClick={() => startEditingPokemon(p)}
                      className="edit-pokemon-button"
                    >
                      Edit
                    </button>
                    <button 
                      onClick={() => handleDeletePokemon(p.id, p.nickname || p.pokemon_name)}
                      className="delete-pokemon-button"
                    >
                      Remove
                    </button>
                  </div>
                </>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default TrainerPokemon;

// src/vuejs/vue-frontend/src/views/TrainerPokemon.vue
<script setup>
import { ref, onMounted, computed } from "vue";
import { useRoute, useRouter } from "vue-router";
import { usePokemonStore } from "@/stores/pokemon";
import { useTrainersStore } from "@/stores/trainers";
import ApiService from "@/services/api";

const route = useRoute();
const router = useRouter();
const pokemonStore = usePokemonStore();
const trainersStore = useTrainersStore();

const trainerId = parseInt(route.params.id);

// Component state
const trainer = ref(null);
const pokemon = computed(() => pokemonStore.trainerPokemon);
const loading = computed(() => pokemonStore.loading);
const error = computed(() => pokemonStore.error);

// Form state for adding Pokemon
const showAddForm = ref(false);
const showEditForm = ref(false);
const editingPokemon = ref(null);
const isSubmitting = ref(false);

// Form data
const pokemonForm = ref({
  pokemon_id: null,
  nickname: "",
  level: 1,
  iv_hp: 0,
  iv_attack: 0,
  iv_defense: 0,
  iv_special: 0,
  iv_speed: 0,
  ev_hp: 0,
  ev_attack: 0,
  ev_defense: 0,
  ev_special: 0,
  ev_speed: 0,
});

// Delete confirmation
const showDeleteConfirm = ref(false);
const pokemonToDelete = ref(null);
const isDeleting = ref(false);

// Load trainer and Pokemon data
onMounted(async () => {
  try {
    // Load trainer info
    trainer.value = await ApiService.getTrainer(trainerId);
    // Load trainer's Pokemon
    await pokemonStore.fetchTrainerPokemon(trainerId);
  } catch (err) {
    console.error("Failed to load data:", err);
  }
});

// Reset form
const resetForm = () => {
  pokemonForm.value = {
    pokemon_id: null,
    nickname: "",
    level: 1,
    iv_hp: 0,
    iv_attack: 0,
    iv_defense: 0,
    iv_special: 0,
    iv_speed: 0,
    ev_hp: 0,
    ev_attack: 0,
    ev_defense: 0,
    ev_special: 0,
    ev_speed: 0,
  };
};

// Show add form
const showAddPokemonForm = () => {
  resetForm();
  showAddForm.value = true;
  showEditForm.value = false;
};

// Show edit form
const showEditPokemonForm = (pokemonData) => {
  pokemonForm.value = { ...pokemonData };
  editingPokemon.value = pokemonData;
  showEditForm.value = true;
  showAddForm.value = false;
};

// Cancel form
const cancelForm = () => {
  showAddForm.value = false;
  showEditForm.value = false;
  editingPokemon.value = null;
  resetForm();
};

// Submit form (add or edit)
const submitPokemonForm = async () => {
  if (!pokemonForm.value.pokemon_id || !pokemonForm.value.nickname.trim()) {
    error.value = "Pokemon ID and nickname are required";
    return;
  }

  isSubmitting.value = true;

  try {
    // Ensure all required fields are present and properly typed
    const pokemonData = {
      trainer_id: trainerId, // Make sure trainer_id is included
      pokemon_id: parseInt(pokemonForm.value.pokemon_id),
      nickname: pokemonForm.value.nickname.trim(),
      level: parseInt(pokemonForm.value.level) || 1,
      iv_hp: parseInt(pokemonForm.value.iv_hp) || 0,
      iv_attack: parseInt(pokemonForm.value.iv_attack) || 0,
      iv_defense: parseInt(pokemonForm.value.iv_defense) || 0,
      iv_special: parseInt(pokemonForm.value.iv_special) || 0,
      iv_speed: parseInt(pokemonForm.value.iv_speed) || 0,
      ev_hp: parseInt(pokemonForm.value.ev_hp) || 0,
      ev_attack: parseInt(pokemonForm.value.ev_attack) || 0,
      ev_defense: parseInt(pokemonForm.value.ev_defense) || 0,
      ev_special: parseInt(pokemonForm.value.ev_special) || 0,
      ev_speed: parseInt(pokemonForm.value.ev_speed) || 0,
    };

    console.log("Submitting Pokemon data:", pokemonData); // Debug log

    if (showEditForm.value && editingPokemon.value) {
      // Update existing Pokemon
      await pokemonStore.updateTrainerPokemon(trainerId, editingPokemon.value.id, pokemonData);
    } else {
      // Add new Pokemon
      await pokemonStore.createTrainerPokemon(trainerId, pokemonData);
    }

    // Refresh Pokemon list
    await pokemonStore.fetchTrainerPokemon(trainerId);
    cancelForm();
  } catch (err) {
    console.error("Failed to save Pokemon:", err);
    error.value = "Failed to save Pokemon. Please check the console for details.";
  } finally {
    isSubmitting.value = false;
  }
};

// Show delete confirmation
const showDeleteConfirmation = (pokemonData) => {
  pokemonToDelete.value = pokemonData;
  showDeleteConfirm.value = true;
};

// Cancel delete
const cancelDelete = () => {
  showDeleteConfirm.value = false;
  pokemonToDelete.value = null;
};

// Confirm delete
const confirmDelete = async () => {
  if (!pokemonToDelete.value) return;

  isDeleting.value = true;

  try {
    await pokemonStore.deleteTrainerPokemon(trainerId, pokemonToDelete.value.id);
    await pokemonStore.fetchTrainerPokemon(trainerId);
  } catch (err) {
    console.error("Failed to delete Pokemon:", err);
  } finally {
    isDeleting.value = false;
    showDeleteConfirm.value = false;
    pokemonToDelete.value = null;
  }
};
</script>

<template>
  <div class="trainer-pokemon">
    <!-- Header -->
    <div class="header-section">
      <div>
        <button @click="router.push('/')" class="btn btn-outline btn-small">
          ← Back to Trainers
        </button>
        <h1 v-if="trainer">{{ trainer.name }}'s Pokemon Team</h1>
        <h1 v-else>Pokemon Team</h1>
      </div>
      <button @click="showAddPokemonForm" class="btn btn-primary">+ Add Pokemon</button>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="loading">Loading Pokemon...</div>

    <!-- Error -->
    <div v-if="error" class="error">
      <p>{{ error }}</p>
      <button @click="pokemonStore.clearError()" class="btn btn-small">Clear Error</button>
    </div>

    <!-- Pokemon List -->
    <div v-if="!loading && !error" class="pokemon-section">
      <div v-if="pokemon.length === 0" class="empty">
        <p>This trainer has no Pokemon yet.</p>
        <button @click="showAddPokemonForm" class="btn btn-primary">Add First Pokemon</button>
      </div>

      <div v-else class="pokemon-grid">
        <div v-for="poke in pokemon" :key="poke.id" class="pokemon-card">
          <!-- Pokemon Header with name and species -->
          <div class="pokemon-header">
            <h3>{{ poke.nickname || poke.pokemon_name }}</h3>
            <p v-if="poke.nickname" class="pokemon-species">({{ poke.pokemon_name }})</p>
          </div>

          <div class="pokemon-details">
            <p><strong>Level:</strong> {{ poke.level }}</p>
            <p v-if="poke.type1">
              <strong>Type:</strong> {{ poke.type1
              }}<span v-if="poke.type2"> / {{ poke.type2 }}</span>
            </p>
          </div>

          <!-- Calculated Stats Section -->
          <div v-if="poke.calculated_hp" class="stats-section">
            <h4>Calculated Stats</h4>
            <div class="stats-grid calculated-stats">
              <span>HP: {{ poke.calculated_hp }}</span>
              <span>ATK: {{ poke.calculated_attack }}</span>
              <span>DEF: {{ poke.calculated_defense }}</span>
              <span>SPD: {{ poke.calculated_speed }}</span>
              <span>SPC: {{ poke.calculated_special }}</span>
            </div>
          </div>

          <!-- IVs Section -->
          <div class="stats-section">
            <h4>Individual Values (IVs)</h4>
            <div class="stats-grid">
              <span>ATK: {{ poke.iv_attack }}</span>
              <span>DEF: {{ poke.iv_defense }}</span>
              <span>SPD: {{ poke.iv_speed }}</span>
              <span>SPC: {{ poke.iv_special }}</span>
            </div>
          </div>

          <!-- EVs Section (optional - you can remove if not needed) -->
          <div class="stats-section">
            <h4>Effort Values (EVs)</h4>
            <div class="stats-grid">
              <span>HP: {{ poke.ev_hp }}</span>
              <span>ATK: {{ poke.ev_attack }}</span>
              <span>DEF: {{ poke.ev_defense }}</span>
              <span>SPD: {{ poke.ev_speed }}</span>
              <span>SPC: {{ poke.ev_special }}</span>
            </div>
          </div>

          <div class="pokemon-actions">
            <button @click="showEditPokemonForm(poke)" class="btn btn-secondary btn-small">
              Edit
            </button>
            <button @click="showDeleteConfirmation(poke)" class="btn btn-danger btn-small">
              Delete
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Add/Edit Pokemon Form -->
    <div v-if="showAddForm || showEditForm" class="modal-overlay" @click="cancelForm">
      <div class="modal-content large-modal" @click.stop>
        <h3>{{ showEditForm ? "Edit Pokemon" : "Add New Pokemon" }}</h3>

        <form @submit.prevent="submitPokemonForm" class="pokemon-form">
          <div class="form-row">
            <div class="form-group">
              <label for="pokemon_id">Pokemon ID *</label>
              <input
                id="pokemon_id"
                v-model="pokemonForm.pokemon_id"
                type="number"
                min="1"
                max="151"
                required
                :disabled="isSubmitting"
              />
            </div>

            <div class="form-group">
              <label for="nickname">Nickname *</label>
              <input
                id="nickname"
                v-model="pokemonForm.nickname"
                type="text"
                required
                :disabled="isSubmitting"
              />
            </div>

            <div class="form-group">
              <label for="level">Level</label>
              <input
                id="level"
                v-model="pokemonForm.level"
                type="number"
                min="1"
                max="100"
                :disabled="isSubmitting"
              />
            </div>
          </div>

          <h4>Individual Values (IVs)</h4>
          <div class="form-row">
            <div class="form-group">
              <label>HP IV</label>
              <input
                v-model="pokemonForm.iv_hp"
                type="number"
                min="0"
                max="15"
                :disabled="isSubmitting"
              />
            </div>
            <div class="form-group">
              <label>Attack IV</label>
              <input
                v-model="pokemonForm.iv_attack"
                type="number"
                min="0"
                max="15"
                :disabled="isSubmitting"
              />
            </div>
            <div class="form-group">
              <label>Defense IV</label>
              <input
                v-model="pokemonForm.iv_defense"
                type="number"
                min="0"
                max="15"
                :disabled="isSubmitting"
              />
            </div>
            <div class="form-group">
              <label>Special IV</label>
              <input
                v-model="pokemonForm.iv_special"
                type="number"
                min="0"
                max="15"
                :disabled="isSubmitting"
              />
            </div>
            <div class="form-group">
              <label>Speed IV</label>
              <input
                v-model="pokemonForm.iv_speed"
                type="number"
                min="0"
                max="15"
                :disabled="isSubmitting"
              />
            </div>
          </div>

          <h4>Effort Values (EVs)</h4>
          <div class="form-row">
            <div class="form-group">
              <label>HP EV</label>
              <input
                v-model="pokemonForm.ev_hp"
                type="number"
                min="0"
                max="65535"
                :disabled="isSubmitting"
              />
            </div>
            <div class="form-group">
              <label>Attack EV</label>
              <input
                v-model="pokemonForm.ev_attack"
                type="number"
                min="0"
                max="65535"
                :disabled="isSubmitting"
              />
            </div>
            <div class="form-group">
              <label>Defense EV</label>
              <input
                v-model="pokemonForm.ev_defense"
                type="number"
                min="0"
                max="65535"
                :disabled="isSubmitting"
              />
            </div>
            <div class="form-group">
              <label>Special EV</label>
              <input
                v-model="pokemonForm.ev_special"
                type="number"
                min="0"
                max="65535"
                :disabled="isSubmitting"
              />
            </div>
            <div class="form-group">
              <label>Speed EV</label>
              <input
                v-model="pokemonForm.ev_speed"
                type="number"
                min="0"
                max="65535"
                :disabled="isSubmitting"
              />
            </div>
          </div>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary" :disabled="isSubmitting">
              {{ isSubmitting ? "Saving..." : showEditForm ? "Update Pokemon" : "Add Pokemon" }}
            </button>
            <button
              type="button"
              @click="cancelForm"
              class="btn btn-outline"
              :disabled="isSubmitting"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- Delete Confirmation Modal -->
    <div v-if="showDeleteConfirm" class="modal-overlay" @click="cancelDelete">
      <div class="modal-content" @click.stop>
        <h3>Confirm Delete</h3>
        <p>
          Are you sure you want to delete <strong>{{ pokemonToDelete?.nickname }}</strong
          >?
          <br />
          <small>This action cannot be undone.</small>
        </p>

        <div class="modal-actions">
          <button @click="confirmDelete" class="btn btn-danger" :disabled="isDeleting">
            {{ isDeleting ? "Deleting..." : "Yes, Delete" }}
          </button>
          <button @click="cancelDelete" class="btn btn-outline" :disabled="isDeleting">
            Cancel
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.trainer-pokemon {
  padding: 20px;
  max-width: 1200px;
  margin: 0 auto;
}

.header-section {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 30px;
}

.header-section h1 {
  margin: 10px 0 0 0;
  color: #333;
}

.loading,
.error,
.empty {
  text-align: center;
  padding: 40px 20px;
}

.error {
  color: #dc3545;
  background-color: #f8d7da;
  border: 1px solid #f5c6cb;
  border-radius: 4px;
  margin-bottom: 20px;
}

.pokemon-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
  gap: 20px;
}

.pokemon-card {
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 20px;
  background-color: #f9f9f9;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.pokemon-header {
  margin-bottom: 15px;
  border-bottom: 2px solid #ecf0f1;
  padding-bottom: 10px;
}

.pokemon-header h3 {
  margin: 0;
  color: #2c3e50;
  font-size: 1.4em;
}

.pokemon-species {
  margin: 5px 0 0 0;
  color: #7f8c8d;
  font-style: italic;
  font-size: 14px;
}

.calculated-stats {
  background-color: #e8f5e8;
  padding: 10px;
  border-radius: 6px;
  font-weight: 600;
}

.calculated-stats span {
  color: #2d5a2d;
}

.pokemon-details p {
  margin: 8px 0;
  color: #666;
}

.stats-section {
  margin: 15px 0;
}

.stats-section h4 {
  margin: 0 0 8px 0;
  color: #333;
  font-size: 0.9em;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(70px, 1fr));
  gap: 8px;
  font-size: 0.85em;
  color: #666;
}

.stats-grid span {
  background: #f0f0f0;
  padding: 4px 8px;
  border-radius: 4px;
  text-align: center;
  font-size: 12px;
}

.pokemon-actions {
  margin-top: 15px;
  padding-top: 15px;
  border-top: 1px solid #eee;
  display: flex;
  gap: 10px;
  justify-content: flex-end;
}

/* Modal styles */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
  overflow-y: auto;
}

.modal-content {
  background: white;
  border-radius: 8px;
  padding: 30px;
  max-width: 500px;
  width: 90%;
  text-align: center;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
  margin: 20px;
}

.large-modal {
  max-width: 700px;
  text-align: left;
}

.pokemon-form h4 {
  margin: 20px 0 10px 0;
  color: #333;
}

.form-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 15px;
  margin-bottom: 15px;
}

.form-group {
  display: flex;
  flex-direction: column;
}

.form-group label {
  margin-bottom: 5px;
  font-weight: bold;
  color: #333;
  font-size: 0.9em;
}

.form-group input {
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
}

.form-group input:focus {
  outline: none;
  border-color: #007bff;
  box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
}

.form-actions {
  display: flex;
  gap: 15px;
  justify-content: center;
  margin-top: 30px;
}

.btn {
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  font-weight: bold;
  text-decoration: none;
  display: inline-block;
  transition: background-color 0.2s;
}

.btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.btn-small {
  padding: 5px 15px;
  font-size: 12px;
}

.btn-primary {
  background-color: #007bff;
  color: white;
}

.btn-primary:hover:not(:disabled) {
  background-color: #0056b3;
}

.btn-secondary {
  background-color: #6c757d;
  color: white;
}

.btn-secondary:hover:not(:disabled) {
  background-color: #5a6268;
}

.btn-danger {
  background-color: #dc3545;
  color: white;
}

.btn-danger:hover:not(:disabled) {
  background-color: #c82333;
}

.btn-outline {
  background-color: transparent;
  color: #007bff;
  border: 1px solid #007bff;
}

.btn-outline:hover:not(:disabled) {
  background-color: #007bff;
  color: white;
}

.modal-actions {
  display: flex;
  gap: 15px;
  justify-content: center;
}
</style>
